
import type { RuntimeError, StaticAnalysisResponse, GitHubPushRequest } from '../../services/sandbox/sandboxTypes';
import type { FileOutputType, PhaseConceptType } from '../schemas';
import type { ConversationMessage } from '../inferutils/common';
import type { InferenceContext } from '../inferutils/config.types';
import type { TemplateDetails } from '../../services/sandbox/sandboxTypes';
import { TemplateSelection } from '../schemas';
import { CurrentDevState, PhasicState, AgenticState } from './state';
import { ProcessedImageAttachment } from 'worker/types/image-attachment';

export type BehaviorType = 'phasic' | 'agentic';

export type ProjectType = 'app' | 'workflow' | 'presentation' | 'general';

/**
 * Chat execution mode.
 * - 'plan': only analyze the request and produce an Implementation Plan. No
 *   files, database, config, migrations or deployments are mutated.
 * - 'build': implement the change (current default behavior).
 */
export type ChatMode = 'plan' | 'build';

export type PlanStatus = 'draft' | 'approved' | 'superseded' | 'implemented';

/**
 * Resolve a chat mode from untrusted input. Defaults to 'plan' so a request
 * never builds/mutates the project unless the user explicitly chose 'build'.
 */
export function resolveChatMode(mode: unknown): ChatMode {
    return mode === 'build' ? 'build' : 'plan';
}

/** Structured implementation plan produced in Plan mode. */
export interface ImplementationPlan {
    id: string;
    sessionId: string;
    title: string;
    goal: string;
    assumptions: string[];
    affectedModules: string[];
    userFlow: string[];
    dataModelImpact: string[];
    apiImpact: string[];
    uiChanges: string[];
    edgeCases: string[];
    acceptanceCriteria: string[];
    implementationSteps: string[];
    status: PlanStatus;
    createdAt: string;
    updatedAt: string;
}

/**
 * Runtime type - WHERE it runs during dev
 * - sandbox: Cloudflare Containers (full apps with UI)
 * - worker: Dynamic Worker Loaders (backend only)  
 * - none: No runtime (static export only)
 */
export type RuntimeType = 'sandbox' | 'worker' | 'none';

/** Base initialization arguments shared by all agents */
interface BaseAgentInitArgs {
    query: string;
    hostname: string;
    inferenceContext: InferenceContext;
    language?: string;
    frameworks?: string[];
    images?: ProcessedImageAttachment[];
    onBlueprintChunk: (chunk: string) => void;
    sandboxSessionId?: string; // Generated by CodeGeneratorAgent, passed to behavior
    mode?: ChatMode; // 'plan' (analyze only) or 'build' (implement). Defaults to 'plan'.
    // Import flow: seed the session with files from an external project instead of starting bare.
    externalFiles?: Array<{ filePath: string; fileContents: string }>;
    importSource?: 'zip' | 'github' | 'template';
    /** P2: seed a Supabase auth + RBAC scaffold and steer generation to build on it. */
    useSupabase?: boolean;
}

/** Phasic agent initialization arguments */
interface PhasicAgentInitArgs extends BaseAgentInitArgs {
    templateInfo: {
        templateDetails: TemplateDetails;
        selection: TemplateSelection;
    };
}

/** Agentic agent initialization arguments */
interface AgenticAgentInitArgs extends BaseAgentInitArgs {
    templateInfo?: {
        templateDetails: TemplateDetails;
        selection: TemplateSelection;
    };
}

/** Generic initialization arguments based on state type */
export type AgentInitArgs<TState extends PhasicState | AgenticState = PhasicState | AgenticState> = 
    TState extends PhasicState ? PhasicAgentInitArgs : 
    TState extends AgenticState ? AgenticAgentInitArgs : 
    PhasicAgentInitArgs | AgenticAgentInitArgs;

export type Plan = string;

export interface AllIssues {
    runtimeErrors: RuntimeError[];
    staticAnalysis: StaticAnalysisResponse;
}

/**
 * Agent state definition for code generation
 */
export interface ScreenshotData {
    url: string;
    timestamp: number;
    viewport: { width: number; height: number };
    userAgent?: string;
    screenshot?: string; // Base64 data URL from Cloudflare Browser Rendering REST API
}

export interface AgentSummary {
    query: string;
    generatedCode: FileOutputType[];
    conversation?: ConversationMessage[];
}

export interface UserContext {
    suggestions?: string[];
    images?: ProcessedImageAttachment[];  // Image URLs
}

export interface PhaseExecutionResult {
    currentDevState: CurrentDevState;
    staticAnalysis?: StaticAnalysisResponse;
    result?: PhaseConceptType;
    userSuggestions?: string[];
    userContext?: UserContext;
}

/**
 * Result type for deep debug operations
 */
export type DeepDebugResult = 
    | { success: true; transcript: string }
    | { success: false; error: string };

export type DeploymentTarget = 'platform' | 'user';

export interface DeployResult {
    success: boolean;
    target: DeploymentTarget;
    url?: string;
    deploymentId?: string;
    error?: string;
    metadata?: Record<string, unknown>;
}

export interface DeployOptions {
    target?: DeploymentTarget;
    token?: string;
    metadata?: Record<string, unknown>;
}

/**
 * Result of project export/deployment operation
 */
export interface ExportResult {
    success: boolean;
    url?: string;
    error?: string;
    metadata?: Record<string, unknown>;
}

/**
 * Options for project export/deployment
 */
export interface ExportOptions {
    kind: 'github' | 'pdf' | 'pptx' | 'googleslides' | 'workflow';
    format?: string;
    token?: string;
    github?: GitHubPushRequest;
    metadata?: Record<string, unknown>;
}
